name: 🔖 Documentation update
description: Improve Documentation
title: '[Docs]:'
labels: ['documentation']
body:
  - type: textarea
    id: improve-docs
    attributes:
      label: what's wrong with the documentation?
      description: which things do we need to add?
      placeholder: Add description
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Add screenshots
      description: Add screenshots to see the demo
      placeholder: Add screenshots
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: 'Record'
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
