version: '3.7'

secrets:
  tls-key:
    file: ./tls/key.pem
configs:
  tls-cert:
    file: ./tls/cert.pem

services:
  proxy:
    environment:
      BASE_URL: ${BASE_URL:-https://local.livecycle.run:8443}
    secrets:
      - source: tls-key
        target: /app/tls/key.pem
    configs:
      - source: tls-cert
        target: /app/tls/cert.pem
    ports:
      - '8030:3000'
      - '8443:8443'
      - '2223:2222'
