#cloud-config

write_files:
- path: /etc/systemd/system/nodeexporter.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=Run the node-exporter Docker container
    Requires=docker.service
    After=docker.service

    [Service]
    ExecStart=docker run \
      --restart unless-stopped \
      --name node-exporter \
      --network=host  \
      --pid=host \
      -v "/:/host:ro,rslave" \
      --security-opt apparmor=unconfined \
      quay.io/prometheus/node-exporter:latest \
        --path.rootfs=/host

    ExecStop=/usr/bin/docker stop node-exporter
    ExecStopPost=/usr/bin/docker rm node-exporter

runcmd:
- systemctl daemon-reload
- systemctl start nodeexporter.service
