apiVersion: v1
kind: ConfigMap
metadata:
  name: preevy-myprofile-docker-config
data:
  daemon.json: |
    {
      "tls": false
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: preevy-myprofile
  labels:
    app: preevy-myprofile-myenv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preevy-myprofile-myenv
  template:
    metadata:
      labels:
        app: preevy-myprofile-myenv
    spec:
      containers:
      - name: docker
        image: docker:24-dind
        securityContext:
          privileged: true
        command: ["dockerd", "--host=tcp://0.0.0.0:2375", "--host=unix:///var/run/docker.sock"]
        volumeMounts:
        - mountPath: /etc/docker
          name: docker-config
        - name: agent-socket
          mountPath: /var/run/compose-tunnel-agent
      - name: agent-socat
        image: alpine/socat
        args:
        - tcp-listen:1234,fork,reuseaddr
        - unix-connect:/var/run/compose-tunnel-agent/agent.sock
        ports:
        - containerPort: 1234
          name: agent
          protocol: TCP
        volumeMounts:
        - name: agent-socket
          mountPath: /var/run/compose-tunnel-agent

      volumes:
      - name: docker-config
        configMap:
          name: preevy-myprofile-docker-config
      - name: agent-socket
        emptyDir: {}

        #args: ["--tls=false", "--tlsverify=false", "--host=0.0.0.0:2375"]
        #env:
        #- name: DOCKER_TLS
        #  value: "false"
        #- name: DOCKER_TLS_VERIFY
        #  value: "false"
        #- name: DOCKER_TLS_CERTDIR
        #  value: ""
        #- name: DOCKER_HOST
        #  value: "tcp://0.0.0.0:2375"
