apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"preevy-myprofile-myenv"},"name":"preevy-myprofile","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"preevy-myprofile-myenv"}},"template":{"metadata":{"labels":{"app":"preevy-myprofile-myenv"}},"spec":{"containers":[{"command":["dockerd","--host=tcp://0.0.0.0:2375","--host=unix:///var/run/docker.sock"],"image":"docker:24-dind","name":"docker","securityContext":{"privileged":true},"volumeMounts":[{"mountPath":"/etc/docker","name":"docker-config"},{"mountPath":"/var/run/compose-tunnel-agent","name":"agent-socket"}]},{"args":["tcp-listen:1234,fork,reuseaddr","unix-connect:/var/run/compose-tunnel-agent/agent.sock"],"image":"alpine/socat","name":"agent-socat","ports":[{"containerPort":1234,"name":"agent","protocol":"TCP"}],"volumeMounts":[{"mountPath":"/var/run/compose-tunnel-agent","name":"agent-socket"}]}],"volumes":[{"configMap":{"name":"preevy-myprofile-docker-config"},"name":"docker-config"},{"emptyDir":{},"name":"agent-socket"}]}}}}
  creationTimestamp: "2023-05-28T07:15:25Z"
  generation: 5
  labels:
    app: preevy-myprofile-myenv
  name: preevy-myprofile
  namespace: default
  resourceVersion: "32268"
  uid: 49990249-3f9e-4ca8-a9f5-37fb55d3f351
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: preevy-myprofile-myenv
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: preevy-myprofile-myenv
    spec:
      containers:
      - command:
        - dockerd
        - --host=tcp://0.0.0.0:2375
        - --host=unix:///var/run/docker.sock
        image: docker:24-dind
        imagePullPolicy: Always
        name: docker
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/docker
          name: docker-config
        - mountPath: /var/run/compose-tunnel-agent
          name: agent-socket
      - args:
        - tcp-listen:1234,fork,reuseaddr
        - unix-connect:/var/run/compose-tunnel-agent/agent.sock
        image: alpine/socat
        imagePullPolicy: Always
        name: agent-socat
        ports:
        - containerPort: 1234
          name: agent
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/compose-tunnel-agent
          name: agent-socket
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: preevy-myprofile-docker-config
        name: docker-config
      - emptyDir: {}
        name: agent-socket
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-05-28T07:20:43Z"
    lastUpdateTime: "2023-05-28T07:20:43Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-05-28T07:15:25Z"
    lastUpdateTime: "2023-06-13T07:23:25Z"
    message: ReplicaSet "preevy-myprofile-b858597d8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
