on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]
  push:
    branches: [main]

jobs:
  check-awesome-list-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Check awesome-list linter
        # https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md
        run: npx --yes awesome-lint ./README.md
